### ISSUE TITLE
Harvestcraft plant disappearing

### ISSUE THREAD

**Issue by Isaneefel** [Cuppycake/Mech-and-Magic#31]
When i began setting up a farm for harvestcraft rice  i noticed that established plants from before the update had disappeared and any new seeds i planted tended to disappear after a minute or two and almost instantly if another rice plant was planted beside it. No seed was popped up or anything the plant just disappears.

**Comment by nirobayo** [comment]
I have the same issue. It seems that it "drops" the plant, because enabling seed drop in HarvestCraft's config allows it to drop a seed.

* Seems to happen to Water Garden seeds (rice, cranberry and seaweed). I did not test all the other seeds, but i checked some and they did go fine.
* It happens if you put two seeds planted on any kind of farmland (including mod ones), the former one drops and the new one stays.
* Any kind of normal growth drops the plants. This includes many mod added speeders like the water can. However, Hoe of Growth works fine.

This is impeding me from having underwater vegan meals :P I did not find anything on the Internet, so I think it is something with the recent HarvestCraft update.

**Comment by Cuppycake** [comment]
Thank you for your detailed report. I will pass it on to Pam and see if we can't get it fixed! :)

**Comment by nirobayo** [comment]
@Cuppycake No problem, I just registered here only to show my research :) . Updates on the case would be appreciated anyway.

**Comment by Cuppycake** [comment]
Is this happening on client side as well as on server side?

**Comment by nirobayo** [comment]
I do not know since I play Forever Alone xD but I think I will set up a quick local server to find out.

**Comment by Cuppycake** [comment]
Nope thats good enough as I know @Isaneefel is on our official server :) Thanks.
