### ISSUE TITLE
Another Mod Recommendation

### ISSUE THREAD

**Issue by Gsdigger** [Cuppycake/Mech-and-Magic#34]
What about Infernal Mobs to make it a bit more interesting.

**Comment by Cuppycake** [comment]
Mobs are weird with me haha. If they are added by a much larger mod like blood magic, thaumcraft, etc, then I dont mind them because chances are they are some sort of mechanic in the bigger mod.

I dislike adding mobs just to add mobs. I like the pack to be more about your creativity and building rather than any sort of an RPG feel or constantly worrying about mobs.

**Comment by Gsdigger** [comment]
ok i understand thank you for you time.
